trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'Azure-Service-Connection'

steps:

# =========================
# Step 1: Install Terraform
# =========================
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'


# =========================
# Step 2: Terraform Init
# =========================
- script: terraform init
  displayName: 'Terraform Init'


# =========================
# Step 3: Terraform Validate
# =========================
- script: terraform validate
  displayName: 'Terraform Validate'


# =========================
# Step 4: Terraform Plan
# =========================
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'


# =========================
# Step 5: Terraform Apply
# =========================
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'
